name:                learning-junkie-codex
version:             0.1.0.0
github:              "junkidesu/learning-junkie-codex"
license:             BSD-3-Clause
author:              "Anvar Sheryatullayev"
maintainer:          "alvaro.sh03@gmail.com"
copyright:           "2025 Anvar Sheryatullayev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/junkidesu/learning-junkie-codex#readme>

dependencies:
- base >= 4.7 && < 5
- process 
- directory
- time 
- text 
- bytestring
- uuid
- aeson 
- lens
- openapi3
- servant 
- servant-server 
- servant-client
- openapi3
- servant-openapi3
- servant-swagger-ui
- wai 
- wai-cors
- wai-logger
- warp
- http-client
- file-embed

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  learning-junkie-codex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-junkie-codex

